# Generated by Django 5.1.7 on 2025-03-24 02:48

import django.db.models.deletion
import multipleselectionfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=9, verbose_name='Gênero')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Foto')),
                ('crm', models.CharField(max_length=6, unique=True, verbose_name='CRM')),
                ('hourly_rate', models.IntegerField(blank=True, null=True, verbose_name='Valor por hora')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='Estado')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('pathologies', models.TextField(blank=True, max_length=255, null=True, verbose_name='Patologias')),
                ('services', multipleselectionfield.db.fields.MultipleSelectionField(choices=[('Adolescentes', 'Adolescentes'), ('Adultos', 'Adultos'), ('Crianças', 'Crianças'), ('Idosos', 'Idosos')], max_length=36, verbose_name='Atendimento')),
                ('accepts_agreement', models.BooleanField(verbose_name='Aceita Convênio')),
                ('feedback_followup', models.TextField(default='Não informado', max_length=255, verbose_name='Retorno e Acompanhamento')),
                ('cannabis_experience', models.TextField(max_length=255, verbose_name='Experiência com prescrição de produtos à base de cannabis')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Especalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255, verbose_name='Universidade')),
                ('course', models.CharField(max_length=255, verbose_name='Curso')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_education', to='doctors.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_specialty', to='doctors.specialty', verbose_name='Especialidade'),
        ),
    ]
