# Generated by Django 5.1.7 on 2025-03-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cannabis_experience',
            field=models.TextField(default='Não informado', max_length=255, verbose_name='Experiência com prescrição de produtos à base de cannabis'),
        ),
    ]
