# Generated by Django 5.1.7 on 2025-03-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_cannabis_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cannabis_experience',
            field=models.TextField(default='Não informado', verbose_name='Experiência com prescrição de produtos à base de cannabis'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
