# Generated by Django 5.1.7 on 2025-03-24 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_cannabis_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='educations', to='doctors.doctor'),
        ),
    ]
