# Generated by Django 5.1.7 on 2025-03-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_education_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='pathologies',
            field=models.TextField(blank=True, null=True, verbose_name='Patologias'),
        ),
    ]
