# Generated by Django 5.1.7 on 2025-03-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_remove_doctor_hourly_rate_doctor_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor'),
        ),
    ]
